export * from './types.js';
export { loadConfig } from './config/load.js';
export type { Config } from './config/schema.js';
export { StateStore } from './state/store.js';
export type { StateFile, StatePage } from './state/schema.js';
export { discoverPages, fetchSitemapPaths, crawlPaths } from './discovery/index.js';
export { PageCapturer } from './capture/capturer.js';
export type { CaptureInput, CaptureResult, CaptureViewportResult } from './capture/capturer.js';
export { resolveViewports } from './capture/viewport.js';
export { pixelDiff } from './diff/pixel.js';
export type { PixelDiffResult } from './diff/pixel.js';
export { MigrationEngine } from './engine/migration.js';
export type { MigrationInit, MigrationResumeOpts, EngineStatus } from './engine/migration.js';
export { extractClusters } from './diff/clusters.js';
export type { ExtractClustersOptions } from './diff/clusters.js';
export { elementAtPoint } from './analysis/element-at-point.js';
export type { Point } from './analysis/element-at-point.js';
export { compareStyles, STYLE_WHITELIST } from './analysis/style-compare.js';
export { generateFixProposals } from './analysis/fix-proposals.js';
export type { GenerateFixProposalsInput } from './analysis/fix-proposals.js';
export { captureDomSnapshot } from './capture/dom-snapshot.js';
export type { CaptureDomSnapshotOptions } from './capture/dom-snapshot.js';
